### PR TITLE
Update bzip2 download url

### PR DESCRIPTION
**Pull request by hakonhagland**
This fixes issue #28 for me.

### CODE REVIEW

**Review by genio — CHANGES_REQUESTED** [review]
We don't need to remove old versions from the sources.list file

**Comment by genio** [comment]
The old link could be updated to reflect their current location: https://sourceware.org/pub/bzip2/bzip2-1.0.6.tar.gz

**Comment by hakonhagland** [comment]
> The old link could be updated to reflect their current location

@genio Good idea, I have updated the PR.

**Comment by genio** [comment]
Apologies. I think I confused you because I didn't explain much.

You can have multiple versions listed in the `sources.list` file and just use the version you want in the actual build script, `5034`. So, if you want to leave both 1.0.6 and 1.0.8 in the `sources.list` you can do that with no problem. If there's a good reason to move up from 1.0.6 to whatever the latest version is, you just add the new version to the list and change the build script to use the new version.

**Comment by hakonhagland** [comment]
>  So, if you want to leave both 1.0.6 and 1.0.8 in the sources.list you can do that with no problem.

@genio So this is because of line 227:

https://github.com/StrawberryPerl/build-extlibs/blob/d20a2326562d58910c8011420ceb762d64cbabd7/build.sh#L227

the `head -n 1` will select the first match, right? Anyway, I am not sure I see a problem with the current `sources.list` in this PR. It has been updated to the correct URL now, right? Did you mean that I should leave the old http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz in there too?

**Comment by genio** [comment]
I meant you could leave both 1.0.6 and 1.0.8 in there. Where you removed https://github.com/StrawberryPerl/build-extlibs/pull/29/files#diff-b4e8afd31aa7fe64e519b78a18871c7af6444b9ad6986484a5d457d7693b2179L192 1.0.8, you could have the following.

in `sources.list`:
```
#### bzip2
#URL http://www.sourceware.org/
https://sourceware.org/pub/bzip2/bzip2-1.0.6.tar.gz
https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
```

and then in `5034`:
```
bzip2-1.0.8
```
OR
```
bzip2-1.0.6
```
Depending on what's needed

**Comment by hakonhagland** [comment]
> I meant you could leave both 1.0.6 and 1.0.8 in there.

Ok! good idea. I have updated the PR again.

**Comment by shawnlaffan** [comment]
@genio - is there anything remaining to do on this PR?  I think it can be merged.

**Review by genio — APPROVED** [review]

**Pull request merged**
