### PR TITLE
Update netcdf source location

### PR DESCRIPTION
**Pull request by hakonhagland**
This fixes issue #34 for me.

### CODE REVIEW

**Review by genio — CHANGES_REQUESTED** [review]
Changing the name to v-whatever would be hard to keep up with later. Can you please alias the file like we do here? https://github.com/StrawberryPerl/build-extlibs/blob/fd3391f35c0e75c525fce84df3df8534bd3a5125/sources.list#L207

**Review by genio — APPROVED** [review]

**Comment by hakonhagland** [comment]
>Can you please alias the file like we do here?

@genio Yes that is a more maintainable solution. I have updated the PR.

**Comment by genio** [comment]
Does that build correctly without need for patching?

**Comment by hakonhagland** [comment]
> Does that build correctly without need for patching?

@genio I started a new build now. It seems to download fine, here is the output from that part: 
```
[...]

### netcdf-c-4.9.0
2023-02-16 20:04:57 URL:https://codeload.github.com/Unidata/netcdf-c/tar.gz/refs/tags/v4.9.0 [19491744] -> "netcdf-c-4.9.0.tar.gz" [1
]
GONNA Apply: /z/extlib/patches/netcdf-c-4.9.0/0001-no-debug-libraries.patch : /z/extlib/_5034__/netcdf-c-4.9.0.patch.log
GONNA Apply: /z/extlib/patches/netcdf-c-4.9.0/0002-no-file.patch : /z/extlib/_5034__/netcdf-c-4.9.0.patch.log
GONNA Apply: /z/extlib/patches/netcdf-c-4.9.0/2460.patch : /z/extlib/_5034__/netcdf-c-4.9.0.patch.log

[...]
```

the build script has started to build packages, I guess it will take a while before it has finished.

**Comment by shawnlaffan** [comment]
Looks like the patching works.  

FWIW, version 4.9.1 has recently been released.  That version will not need the third patch (2460.patch) but MSYS2 is still using the other two (https://github.com/msys2/MINGW-packages/commit/8d0bb1753bb2b303ce02a299f06c0735ffb5a5ce).  I'll look into it if I get a chance but it's not critical that we upgrade.

**Pull request merged**
