### PR TITLE
get fontconfig build working

### PR DESCRIPTION
**Pull request by shawnlaffan**
build fribidi 1.0.12
install msys packages for gettext-devel and gperf 

The second step should probably be in the main spbuild repo but is useful here as it saves rerunning the spbuild setup if already in a shell running the builds.  

Updates #7

### CODE REVIEW

**Comment by genio** [comment]
I would prefer moving the additional prereqs into the spbuild repo. Having them here would run that each and every time we run build.sh.

**Comment by shawnlaffan** [comment]
I'll modify the commit and force push.  

FWIW, the commands check if the package is installed (the ```pacman -Qkq``` call) and only run the install if needed.  It is cleaner if there are no pacman calls in the build script, though.

**Comment by shawnlaffan** [comment]
gettext-devel and gperf now in PR https://github.com/StrawberryPerl/spbuild/pull/6

**Comment by shawnlaffan** [comment]
Thanks for merging.  Just a note that this also depends on https://github.com/StrawberryPerl/spbuild/pull/6

**Pull request merged**
